# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Fetch the provisioning profiles
    match(type: "development")

    # Build the app with automatic signing enabled
    build_app(
      workspace: "CheckCICD.xcworkspace", 
      scheme: "CheckCICD",
      export_method: "development", # Adjust according to your needs
      export_options: {
        provisioningProfiles: {
          "CheckCICD" => "check CICD 3TYP89QWY5" # Change to your app's bundle ID
        },
        signingStyle: "automatic" # This enables automatic signing
      },
      allow_provisioning_updates: true # Allows Xcode to manage profiles
    )

    # Other actions can be added here if needed
  end
end
