name: GitHub Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: GitHub Pipeline
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app
        
      - name: Running Xcode version Is?
        run: /usr/bin/xcodebuild -version
   
      - name: Build Cleanup
        run: |
          xcodebuild clean -project GitHubAction.xcodeproj -scheme GitHubAction | xcpretty
          
      - name: Build Test
        run: |
          xcodebuild test -project GitHubAction.xcodeproj -scheme GitHubAction -destination 'platform=iOS   Simulator,name=iPhone 14,OS=16.2' | xcpretty -s
