name: Swift CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update CocoaPods
        run: sudo gem install cocoapods

      - name: List files in checkcicd directory
        run: ls -la ./checkcicd

      - name: Clean CocoaPods cache
        run: pod cache clean --all

      - name: Install CocoaPods with logs
        working-directory: ./checkcicd  # Adjust this to the correct project directory
        run: pod install --repo-update
        continue-on-error: false
        id: pod_install
  
      - name: Install CocoaPods with repo update
        working-directory: ./checkcicd  # Adjust the path if necessary
        run: pod install --repo-update

      - name: Clean project
        run: xcodebuild clean -scheme CheckCICD

      - name: Build project
        run: |
          xcodebuild -workspace CheckCICD.xcworkspace -scheme CheckCICD -configuration Debug -sdk iphoneos -allowProvisioningUpdates clean build
