name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the app
      run:  xcodebuild CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO platform=iOS Simulator,name=iPhone 14,OS=16.0
