name: Distribute_Firebase_Dev

on:
  workflow_dispatch:
    inputs:
      notes:
        default: ""
        description: Firebase release notes


jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Pod Install
        working-directory: ./
        run: pod install
        continue-on-error: true
        id: pod1
      - name: Trying to fix in case of failed (1)
        working-directory: ./
        continue-on-error: true
        id: pod2
        if: steps.pod1.outcome == 'failure'
        run: |
            echo "Run pod install again with repo update"
            pod install --repo-update
      - name: Trying to fix in case of failed (2)
        working-directory: ./
        continue-on-error: true
        id: pod3
        if: steps.pod2.outcome == 'failure'
        run: |
            echo "Run pod install again as x86"
            arch -x86_64 pod install
      - name: Trying to fix in case of failed (3)
        working-directory: ./
        if: steps.pod3.outcome == 'failure'
        run: |
            echo "Run pod install again as x84 with repo update"
            arch -x86_64 pod install --repo-update
      - name: Build Staging
        run: bundle exec fastlane job_build env:dev
      - name: Cleanup archives
        run: find ~/Library/Developer/Xcode/Archives -ctime +7 -maxdepth 1 -print0 -exec rm -f -r {} \;
