name: GitHub Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: GitHub Pipeline
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode.app
        
      - name: Running Xcode version Is?
        run: /usr/bin/xcodebuild -version
   
      - name: Build Cleanup
        run: |
          xcodebuild clean -project GitHubAction.xcodeproj -scheme GitHubAction | xcpretty
          
      - name: Build project
        run: |
          xcodebuild -workspace CheckCICD.xcworkspace -scheme CheckCICD -configuration Debug -sdk iphoneos -allowProvisioningUpdates clean build
